### ISSUE TITLE
Enhanced health authorization

### ISSUE THREAD

**Issue by joyitas** [aws/elastic-beanstalk-roadmap#107]
Recently, we added an option to require authorization of enhanced health information traffic from environment instances to the Elastic Beanstalk service. Beanstalk instances use an API to communicate enhanced health information traffic from environment instances to the service. By adding authorization for this API, you can prevent bad actors from spoofing health data. For more details, see release notes https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-09-10-healthd-authz.html. 
If you have any questions, please add a comment in the issue.

**Comment by nikhilo6july** [comment]
How to enable this option and where ?

**Comment by rapgithub** [comment]
I do not understand this from AWS that modify things with Enhanced health authorization and someone ask how to disable it or add the permission and nobody replies I have done a research online for days and nothing is clear! please AWS add a simple way to user know how to disable that because is making all my environment to fail! 
thanks
