### ISSUE TITLE
Ruby on Amazon Linux 2 platform (BETA)

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#12]
We're working on building out this and other platforms on top of Amazon Linux 2 (AL2). With our AL2 platforms, we are refreshing and rethinking each platform based on feedback we’ve gotten from customers. If you have any questions or suggestions for this platform, please add a comment in the issue.

**Comment by sskylar** [comment]
How can one sign up for the beta?

**Comment by labisso** [comment]
@sskylar When launched this will be a public beta, so no signup is required. You'll see the beta platform available in the Elastic Beanstalk console and APIs.

**Comment by stefansundin** [comment]
Is the reason that Ruby 2.7 is taking so long because you want to use it as a beta for AL2? Is there any timeline?

I'm guessing that since Python 3.7 has only been released for the AL2 beta, we won't be seeing any overlap in version support between AL and AL2?

Thanks!

**Comment by labisso** [comment]
hi @stefansundin - there will be overlap in runtime version availability between AL and AL2 platforms. Generally on AL2 we are supporting runtime versions which are available from the source we consume from, and are not approaching upstream end-of-support. For Python, we only started off with Python 3.7 support because that's what is currently available in AL2 repositories.

We're working on our Ruby AL2 beta right now, which includes 2.7. Would it be very valuable for you to have 2.7 available sooner on AL? We can evaluate doing that.

**Comment by stefansundin** [comment]
Hi @labisso.

It's really no rush, but it may just be the natural order to release 2.7 in, especially since EB got Ruby 2.6 on January 23rd of last year (i.e. about a month after its release).

I have the habit of upgrading shortly after a new major release. I deploy this app on both Heroku and EB, and I won't upgrade the Ruby version unless the new version is available on both. Heroku usually makes new versions available on the same day that it is released (even release candidates), which may not be so strange considering that they have hired Matz.

**Comment by susana-hernandez** [comment]
Hi,
I'm trying to test this platform, but i'm gettin an error and I think that maybe is related to this instruction 'Running command /bin/sh -c bundle install --deployment', I didn't put this instrucción in any of my  configurations, also I tried to change this Environment variable BUNDLER_DEPLOYMENT_MODE to 'false' but I'm getting the same error and I can't change it. 
I would appreciate your help


 error logs:
----------------------------------------------------------------------------------------------------------------------------
2020/04/16 23:00:30.925335 [INFO] Executing instruction: StageApplication
2020/04/16 23:00:30.925555 [INFO] extracting /opt/elasticbeanstalk/deployment/app_source_bundle to /var/app/staging/
2020/04/16 23:00:30.925589 [INFO] Running command /bin/sh -c /usr/bin/unzip -q -o /opt/elasticbeanstalk/deployment/app_source_bundle -d /var/app/staging/
2020/04/16 23:00:30.946860 [INFO] finished extracting /opt/elasticbeanstalk/deployment/app_source_bundle to /var/app/staging/ successfully
2020/04/16 23:00:30.950390 [INFO] Executing instruction: RunPreBuildHooks
2020/04/16 23:00:30.950426 [INFO] The dir .platform/hooks/prebuild/ does not exist in the application. Skipping this step...
2020/04/16 23:00:30.950431 [INFO] Executing instruction: stage ruby application
2020/04/16 23:00:30.950436 [INFO] stage ruby application ....
2020/04/16 23:00:30.950456 [INFO] No plugin in cfn metadata.
2020/04/16 23:00:30.950491 [INFO] No plugin in cfn metadata.
2020/04/16 23:00:30.950518 [INFO] Running command /bin/sh -c bundle install --deployment
2020/04/16 23:00:31.303155 [ERROR] Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
/opt/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:198: warning: constant Gem::ConfigMap is deprecated
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

The list of sources changed

2020/04/16 23:00:31.303194 [ERROR] An error occurred during execution of command [app-deploy] - [stage ruby application]. Stop running the command. Error: install dependencies in Gemfile failed with error Command /bin/sh -c bundle install --deployment failed with error exit status 16. Stderr:Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
/opt/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:198: warning: constant Gem::ConfigMap is deprecated
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

The list of sources changed


2020/04/16 23:00:31.303200 [INFO] Executing cleanup logic
2020/04/16 23:00:31.303291 [INFO] CommandService Response: {"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"Engine execution has encountered an error.","returncode":1,"events":[]}]}

2020/04/16 23:00:31.303521 [INFO] Platform Engine finished execution on command: app-deploy

#######
INFO: Creating AppVersion app-200416_225936
2020-04-16 22:59:38    INFO    Environment update is starting.
2020-04-16 23:00:19    INFO    Deploying new version to instance(s).
2020-04-16 23:00:34    ERROR   [Instance: i-0d3e206cb1a44446d] Command failed on instance. An unexpected error has occurred [ErrorCode: 0000000001].
2020-04-16 23:00:34    INFO    Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
2020-04-16 23:00:34    ERROR   Unsuccessful command execution on instance id(s) 'i-0d3e206cb1a44446d'. Aborting the operation.
2020-04-16 23:00:35    ERROR   Failed to deploy application.
######


----------------------------------------------------------------------------------------------------------------------------

**Comment by puneeth-k** [comment]
Hi,

In the available Beta Versions, I can see only Puma Application Server.

https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-beta.html#platforms-beta.ruby

Is their any plan for the Passenger Application Server also ?

Please Update.

Thanks
Puneeth

**Comment by Sekhar-Kutikuppala** [comment]
@puneeth-k  AL2 based Ruby platforms. support using Passenger. You can specify `Passenger` in your Gemfile and write start process in your Procfile to run your application.
Example Gemfile
source 'https://rubygems.org'
gem 'passenger'

Example Procfile
web: bundle exec passenger start /var/app/current --socket /var/run/puma/my_app.sock

**Comment by Sekhar-Kutikuppala** [comment]
Ruby on AL2 platform is now generally available
[Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-04-30-al2.html)
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/04/aws-elastic-beanstalk-announces-general-availability-of-amazon-linux-2-based-node-js-php-go-and-ruby-platforms/)

**Comment by urbanrotnik** [comment]
> Hi,
> I'm trying to test this platform, but i'm gettin an error and I think that maybe is related to this instruction 'Running command /bin/sh -c bundle install --deployment', I didn't put this instrucción in any of my configurations, also I tried to change this Environment variable BUNDLER_DEPLOYMENT_MODE to 'false' but I'm getting the same error and I can't change it.
> I would appreciate your help
> 
> ## error logs:
> 2020/04/16 23:00:30.925335 [INFO] Executing instruction: StageApplication
> 2020/04/16 23:00:30.925555 [INFO] extracting /opt/elasticbeanstalk/deployment/app_source_bundle to /var/app/staging/
> 2020/04/16 23:00:30.925589 [INFO] Running command /bin/sh -c /usr/bin/unzip -q -o /opt/elasticbeanstalk/deployment/app_source_bundle -d /var/app/staging/
> 2020/04/16 23:00:30.946860 [INFO] finished extracting /opt/elasticbeanstalk/deployment/app_source_bundle to /var/app/staging/ successfully
> 2020/04/16 23:00:30.950390 [INFO] Executing instruction: RunPreBuildHooks
> 2020/04/16 23:00:30.950426 [INFO] The dir .platform/hooks/prebuild/ does not exist in the application. Skipping this step...
> 2020/04/16 23:00:30.950431 [INFO] Executing instruction: stage ruby application
> 2020/04/16 23:00:30.950436 [INFO] stage ruby application ....
> 2020/04/16 23:00:30.950456 [INFO] No plugin in cfn metadata.
> 2020/04/16 23:00:30.950491 [INFO] No plugin in cfn metadata.
> 2020/04/16 23:00:30.950518 [INFO] Running command /bin/sh -c bundle install --deployment
> 2020/04/16 23:00:31.303155 [ERROR] Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
> installing your bundle as root will break this application for all non-root
> users on this machine.
> /opt/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:198: warning: constant Gem::ConfigMap is deprecated
> You are trying to install in deployment mode after changing
> your Gemfile. Run `bundle install` elsewhere and add the
> updated Gemfile.lock to version control.
> 
> The list of sources changed
> 
> 2020/04/16 23:00:31.303194 [ERROR] An error occurred during execution of command [app-deploy] - [stage ruby application]. Stop running the command. Error: install dependencies in Gemfile failed with error Command /bin/sh -c bundle install --deployment failed with error exit status 16. Stderr:Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
> installing your bundle as root will break this application for all non-root
> users on this machine.
> /opt/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:198: warning: constant Gem::ConfigMap is deprecated
> You are trying to install in deployment mode after changing
> your Gemfile. Run `bundle install` elsewhere and add the
> updated Gemfile.lock to version control.
> 
> The list of sources changed
> 
> 2020/04/16 23:00:31.303200 [INFO] Executing cleanup logic
> 2020/04/16 23:00:31.303291 [INFO] CommandService Response: {"status":"FAILURE","api_version":"1.0","results":[{"status":"FAILURE","msg":"Engine execution has encountered an error.","returncode":1,"events":[]}]}
> 
> 2020/04/16 23:00:31.303521 [INFO] Platform Engine finished execution on command: app-deploy
> 
> #######
> INFO: Creating AppVersion app-200416_225936
> 2020-04-16 22:59:38 INFO Environment update is starting.
> 2020-04-16 23:00:19 INFO Deploying new version to instance(s).
> 2020-04-16 23:00:34 ERROR [Instance: i-0d3e206cb1a44446d] Command failed on instance. An unexpected error has occurred [ErrorCode: 0000000001].
> 2020-04-16 23:00:34 INFO Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
> 2020-04-16 23:00:34 ERROR Unsuccessful command execution on instance id(s) 'i-0d3e206cb1a44446d'. Aborting the operation.
> 2020-04-16 23:00:35 ERROR Failed to deploy application.

@susana-hernandez same issue here. Did you solve this?

**Comment by jamesst20** [comment]
Hi,

I know this might not be the right place, however the first thing that comes up on Google when googling 'EB AL2 Rails' is this.

My Rails app currently works fine on 'Ruby 2.6 With Puma' stack. However I am unable to update to the new AL2 platform.

I am having this error: https://pastebin.com/raw/tRQDwVie

If anyone has a clue that would be awesome

**Comment by januszm** [comment]
I'm working on migrating one Rails application from the Amazon Linux stack to the AL2 stack, and I have some feedback about encountered issues:

* puma server is started without PIDFILE (or at least it is not in /var/run/puma or tmp/pids

* problems with `BUNDLED WITH` in Gemfile.lock:
```
Could not find 'bundler' (1.17.3) required by your /var/app/staging/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run bundle update --bundler.
To install the missing version, run gem install bundler:1.17.3
```

This blocks the deployment process. Would it be possible for EB to detect and use the correct version of the bundler? I am afraid that the entire deployment process may crash as soon as the bundler version specified in BUNDLED WITH in Gemfile.lock and on the EB Ruby platform goes out of sync. As an example of another solution: Heroku reads BUNDLED WITH from Gemfile.lock and uses the appropriate bundler version during the deployment process.

* problems with bundler running as root:

```
 [ERROR] An error occurred during execution of command [self-startup] - [stage ruby application]. Stop running the command. Error: install dependencies in Gemfile failed with error Command /bin/sh -c bundle install failed with error exit status 10. Stderr:Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Could not locate Gemfile
```

* `.bundle/config` owned by root when precompiling assets:
```
/bin/su webapp -c bundle exec rake assets:precompile
There was an error while trying to write to `/var/app/staging/.bundle/config`. It is likely that you need to grant write permissions for that path.
[root@ip staging]# ls -la
drwxr-xr-x 14 webapp webapp  .
drwxr-xr-x  4 root   root       36  ..
drwxr-xr-x 11 webapp webapp  app
drwxr-xr-x  2 root   root       20  .bundle
```

* problems with "directory not empty" errors, e.g. when installing nokogiri or other gems:
```
[ERROR] An error occurred during execution of command [app-deploy] - [StageApplication]. Stop running the command. Error: Recreating Dir failed with error: unlinkat /var/app/staging/vendor/bundle/ruby/2.7.0: directory not empty
[INFO] Executing cleanup logic
```

**UPDATE** I was NOT able to build and deploy even a fresh Rails 6 application to Elastic Beanstalk on Amazon Linux 2 platform with Ruby 2.7 and Puma 5. I think most of the problems me or others described here or somewhere else on the Internet are related to migrating older projects to the new stack. A change to the Puma 5 server is required (otherwise puma turns off with an error message about a v4 vs v5 conflict), an upgrade to bundler 2.1.4 is required, such as on the server, and lastly, it's safer to ger rid of old container commands and convert them to new platform hooks, for example because ENV vars not available like before (only via get config script). When trying to deploy a fresh project I was blocked by the assets:precompile task which fails because `.bundle/config` is owned by root, not webapp user

**Comment by januszm** [comment]
@labisso @Sekhar-Kutikuppala apologies for mentioning you directly, but I'm not sure if this issue is still actively monitored - it is currently impossible to deploy Rails applications on Ruby 2.7 + Amazon Linux 2 platform. The last stable platform is Ruby 2.6 on Amazon Linux 1.

The farthest I was able to reach with deployment was error:

```
/bin/su webapp -c bundle exec rake assets:precompile
There was an error while trying to write to `/var/app/staging/.bundle/config`. It is likely that you need to grant write permissions for that path.
```

Looks like some bundle config commands are executed "as root" and this prevents other steps executed as `webapp`.
Also please have a look at the errors mentioned in my previous message here. It feels like bundler settings are a bit too strict and I think puma should be started with pidfile. There's also an issue with Puma version constraint.

**Comment by ahaverty** [comment]
@januszm did you get anywhere with this since?
Our rails 6, ruby 2.6 + elastic beanstalk Amazon linux 2 environment just dropped off on December 11th
We haven't deployed to it in weeks, and have automatic management disabled.
Attempting to deploy the same application code to our existing application that had worked is hitting the same issue you're reporting above:
```
Stderr:Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
```

Specifically, it's reporting an error with Nokogori:
```
An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.
```

But I've attempted various versions, and I'm confident we had this working for months before it dropped recently, so I believe this is a red herring, and actually related to some recent change to something in amazon (e.g that root user error).

I've since created a brand new elastic beanstalk environment, and I'm still getting the same issues.

I'm also curious about the 4 thumbs up that your comment currently has above, it looks like we're not the only people having the same issue?

**Comment by opposable-crumbs** [comment]
For what it's worth, I'm running the following stack successfully

Ruby 2.7 running on 64bit Amazon Linux 2/3.2.1
Ruby 2.7.2
Rails 6.1

I was never able to get anything working on AL2/3.1.1 or AL2/3.1.2, and I never figured out why. But I was green on AL1/3.1.0 and both 3.2.0 and the newly released 3.2.1 have worked fine for me as well. I don't see anything in the patch notes that would explain this, but you might try spinning up an environment on 3.2.X if you haven't already, just in case.

The only other thing I think I've seen is that for some reason when a deploy fails due to a gem install error, if I wait about 10 minutes and try again it works. Maybe VM lottery? I never really figured that one out either, but I've only seen it a few times.

**Comment by puneetpandey** [comment]
Facing similar issues.
Original Link: https://github.com/rubygems/rubygems/issues/4777
Copy: https://stackoverflow.com/questions/68494462/build-fails-when-deploying-rails-application-on-amazon-linux-2
Note/Summary: I am trying to migrate my existing Rails Application from Amazon Linux AMI to Amazon Linux 2

**Comment by mzfany** [comment]
> @puneeth-k AL2 based Ruby platforms. support using Passenger. You can specify `Passenger` in your Gemfile and write start process in your Procfile to run your application.
> Example Gemfile
> source 'https://rubygems.org'
> gem 'passenger'
> 
> Example Procfile
> web: bundle exec passenger start /var/app/current --socket /var/run/puma/my_app.sock

Hi. i'm trying to use Passenger and followed your instruction above. But I got this error during deployment : 

nginx: [emerg] bind() to unix:/var/run/puma/my_app.sock failed (98: Address already in use)
nginx: [emerg] still could not bind()

Do you know how to solve this issue ? thank you in advance

**Comment by joeyparis** [comment]
> * problems with "directory not empty" errors, e.g. when installing nokogiri or other gems:
> 
> ```
> [ERROR] An error occurred during execution of command [app-deploy] - [StageApplication]. Stop running the command. Error: Recreating Dir failed with error: unlinkat /var/app/staging/vendor/bundle/ruby/2.7.0: directory not empty
> [INFO] Executing cleanup logic
> ```

@januszm were you ever able to find a consistent fix for this error? It happens to me periodically and is completely inconsistent on when it wants to work or not. I can have the same code deployed to the same instance multiple times sometimes it works, sometimes it doesn't. There seems to be no rhyme or reason.
