### ISSUE TITLE
Docker on Amazon Linux 2 platform

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#14]
We're working on building out this and other platforms on top of Amazon Linux 2 (AL2). With our AL2 platforms, we are refreshing and rethinking each platform based on feedback we’ve gotten from customers. If you have any questions or suggestions for this platform, please add a comment in the issue.

**Comment by BobDankert** [comment]
Suggestion: I would love to see the docker environment support running commands within the container prior to making the container live. This would be useful for running application build commands within the container, which need to complete before the container can go live. Currently there are not good ways to accomplish this as part of the eb deploy process with Docker.

**Comment by BobDankert** [comment]
Another suggestion. I have found that adding .ebextensions config container_commands that can take time to complete (on the order of ~5minutes, but observed in tests at 10seconds) in a single docker environment will cause an outage to the app being served by the eb environment while the container_commands: execute. Such as deploying an app update vie "eb deploy" while there is already an app running. The deploy process seems to take down the existing/functional app prior to the commands completing execution, meaning the site returns errors for the duration of the commands. Ideally, there should never be any outage to an app during an eb deploy in this type of situation (my experience with other EB platforms is that these commands run without causing an outage).

**Comment by BobDankert** [comment]
I see this moved to public data. Any idea if either of the items I mentioned above got resolved? Is there any documentation anywhere on the public beta?

**Comment by labisso** [comment]
hi @BobDankert - thanks for the feedback! Our public beta was already in the process of rolling out when your comments came in, so they were not taken into consideration, but we're taking a look at them now. I suggest browsing our [Migrating your Elastic Beanstalk Linux application to Amazon Linux 2](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.migration-al.html) documentation page and in particular the discussion of the new _platform hooks_ functionality. There are more details available in [this page](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html).

Regarding your suggestion to "support running commands within the container prior to making the container live" - how would you picture this working? Like.. is the container running but not serving traffic yet? Or is it more about modifying the container image before starting it?

And I haven't been able to reproduce the container_commands issue you described. Can you provide more details? I'm also curious to know if you still see it in the AL2 beta platform, if you have time to test it. Also you might take a look at the new `predeploy` platform hook, which provides a simpler alternative to container_commands.

**Comment by BobDankert** [comment]
Thanks @labisso for the followup! First off, I'm really excited to see the attention on EB @ AWS so thank you for your work on these things!

As for running commands on the container, this would be helpful if we needed to run simple commands, like `npm ci` or similar, to pull some packages down. I don't want to install node/npm onto my host instance, when it's already part of my docker image, but ideally it should occur on every deployment. I would picture this working with the container running before it is serving traffic (because the container has node/npm, the host does not) but before the transition is made from the previously-running container to the upcoming container.  I do not think support is needed for the second case you described, "Or is it more about modifying the container image before starting it".

As for the container_commands causing outage of the site, I had a very basic isolated and reproducible case where this was occurring. I opened a support case and was more or less told "that's just how it works" so I assumed that's how it was supposed to work. I can replicate this with minimal effort, and was able to cause an outage lasting up to 10minutes with some of my tests by using sleep command in the container_commands: section of .ebextensions. Even without adding sleep commands and without container_commands, if I put options: into the ebextensions I would see an error on the website during a deploy (hitting the website every quarter second during the deploy and monitoring the response, I would see a 5xx error).

I'd be happy to help looking into some of these issues, above, if desired, but more importantly to me is that the outage in particular doesn't occur in the new Docker environment.

**Comment by Sekhar-Kutikuppala** [comment]
Docker on AL2 platform is now generally available. For more information see [What's New post](https://aws.amazon.com/about-aws/whats-new/2020/04/aws-elastic-beanstalk-announces-general-availability-of-amazon-linux-2-based-docker-corretto-and-python-platforms/) and [Release Notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-04-08-al2.html)
