### ISSUE TITLE
Updating DeploymentPolicy in ebextension doesn't work

### ISSUE THREAD

**Issue by wangcarlton** [aws/elastic-beanstalk-roadmap#154]
Hey team,

We are using ebextensions in our application to configure DeploymentPolicy, previously it was Rolling, now we changed it to RollingWithAdditionalBatch, but it seems after deploying, in the Elastic Beanstalk console->Environments->Configuration, the "Rolling updates and deployments"-> "Deployment policy" is still Rolling, not changed after deployments.

It was:
  ```
    aws:elasticbeanstalk:command:
      DeploymentPolicy: Rolling
      BatchSizeType: Fixed
      BatchSize: 1
```
Changed to:
   ```
      aws:elasticbeanstalk:command:
        DeploymentPolicy: RollingWithAdditionalBatch
        BatchSizeType: Fixed
        BatchSize: 1
```
also is there a way to check this config execution logs? I tried checking eb logs under /var/log, nothing quite helpful.
Thanks

**Comment by rahulrajaram** [comment]
Please note that there exists a precedence order w.r.t. option settings wherein option settings set through an API call always take precedence over those set through ebextensions. In fact, you cannot override an option-setting through ebextensions if you've already previously defined it through an API call parameter (`CreateEnvironment`, `DescribeEnvironment`) due to this precedence order [1].

The way forward is for you to make a configuration change through the EB console, or, if you are using the EB CLI through `eb config`. For all such options, see [2].

> also is there a way to check this config execution logs? I tried checking eb logs under /var/log, nothing quite helpful.

In this case, any information published by the EB service will be available through `eb events`.

[1] - https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html#configuration-options-precedence

[2] - https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-configuration-methods-after.html

**Comment by rahulrajaram** [comment]
Closing this Issue as there is no bug.
