### ISSUE TITLE
Ruby v3 support

### ISSUE THREAD

**Issue by kanadatec** [aws/elastic-beanstalk-roadmap#166]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
When will AWS Elastic Beanstalk support Ruby v3?

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Yes, Ruby

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are building a new app and would like to explore setting it up in AWS Elastic Beanstalk, however, we are using Ruby v3 and that version is not yet supported.

**Are you currently working around this issue?**
We are deploying the app manually to an EC2 instance

**Additional context**
Ruby v3 is now stable, and also faster. Reference: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

**Attachments**
N/A

**Comment by januszm** [comment]
In addition to the above, it appears that the Ruby platform on Amazon Linux 2 uses rbenv.
This should greatly simplify the installation of any version of Ruby, e.g. using some hook, e.g. shell script with [rbenv install 3.0](https://github.com/rbenv/rbenv#installing-ruby-versions). Currently, this is not possible, because the install command requires the [rbenv ruby-build plugin](https://github.com/rbenv/ruby-build) to be installed. You could also consider using [rvm](http://rvm.io/) (which I prefer for projects), but it's probably a bit late for that.

**Comment by stefansundin** [comment]
Yeah.. So I am probably going to stop using Elastic Beanstalk for my application since it takes so incredibly long for new Ruby versions to be supported. I host my app on both Heroku and EB, and I think I'll switch over to hosting on Heroku and my own EC2 instance. Heroku literally supports new versions a few hours after it is released, and why it takes AWS 6+ months to support it is so strange.

Oh, another fun problem in EB is that since rbenv is being used, it is very hard to upgrade the Ruby version _if_ you have a `.ruby-version` file present, since you can't deploy new code _and_ upgrade the platform at the same time. It even causes problems on minor version upgrades. So you have to deploy a new environment which is definitely not something you want to do for a platform upgrade.

I wrote a prebuild script that just deletes my `.ruby-version` file which has solved this particular problem for me. But still, I don't feel like this should be needed. If anyone else is interested in it, you can find it here: https://github.com/stefansundin/rssbox/blob/d9e2ef03aa391ad71cea6053c2e3d661e9a91066/.platform/hooks/prebuild/rbenv.sh

I don't see a point in using rbenv in a deployed application either. Just put the ruby binaries on the server, or use ruby-build directly. It's not like we have multiple versions on the server, which is what rbenv is for.

/rant

**Comment by stwr667** [comment]
> Oh, another fun problem in EB is that since rbenv is being used, it is very hard to upgrade the Ruby version _if_ you have a `.ruby-version` file present, since you can't deploy new code _and_ upgrade the platform at the same time. It even causes problems on minor version upgrades. So you have to deploy a new environment which is definitely not something you want to do for a platform upgrade.

@stefansundin I completely agree, rbenv should not be required in a production environment like that.

Your script seems like a good workaround, although here's another approach. They're talking about the Ruby version mentioned in the Gemfile.lock but I assume it could apply to the .rubyversion file too.
https://stackoverflow.com/a/35207353/1852005

**Comment by mybarman** [comment]
Any updates on this @1tonyca

**Comment by mathieujobin** [comment]
I moved from AL1-ruby to use AL2-docker, deployment are much faster, but I've lost the ability to add pre/post deploy hooks ;(

**Comment by 1tonyca** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-11-19-linux.html
