### ISSUE TITLE
Support Node 20.x

### ISSUE THREAD

**Issue by ilu** [aws/elastic-beanstalk-roadmap#304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
I would like to see support for Node 20 in Elastic Beanstalk. 

Node 20 has entered LTS status as of 2023-10-24 and Node 18 has been moved to Maintenance status as of 2023-10-18. Node 18 will have end-of-life on 2025-04-30.

We are in the process of soon having to upgrade our Elastic Beanstalk enviroment and would prefer to go to straight to Node 20 to ensure a longer end-of-life schedule for the environment (end date for Node 14 and Node 16 Elastic Beanstalk enviroments is 2024-06-30).

**Comment by kirill578** [comment]
has anyone considered migrating their environment to docker over eb or ecs? looks like AWS are about 12 months behind the node releases.

**Comment by dev-yesman** [comment]
Why haven't they provided support for Node.js version 20 yet? Do you know anyone who does?

**Comment by simonbrunel** [comment]
FYI, it has been released, probably today since yesterday I upgraded my environments to Node 18.x thinking it would take a few more months before seeing Node 20 supported 😄 Is there any official public roadmap?! If not, that would be useful.


![Screenshot 2024-01-26 at 09 46 21](https://github.com/aws/elastic-beanstalk-roadmap/assets/3874900/c53197f4-a1f6-40b4-9c13-10858f082059)
