### ISSUE TITLE
npm/yarn freeze on platform version 4.2.0 Ruby

### ISSUE THREAD

**Issue by januszm** [aws/elastic-beanstalk-roadmap#345]
**Tell us about your request**
Ruby on Rails with yarn - deployment is impossible after switching to platform version 4.2.0. All `npm` or `yarn` commands freeze when ran in `/var/app/staging`. What's interesting is that `npm install PACKAGE` works fine when executed from a different location, e.g. home folder. This has something to do with disck access to the /var/app/staging directory.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
Newly released 4.2.0 for Ruby

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
npm/yarn freeze in /var/app/staging, deployments fail

**Are you currently working around this issue?**
Downgrade to platform 4.1.0

NOTE: it works fine with the `bun` javascript package manager! Bun is known to be way faster than yarn or npm.

**Comment by praegt** [comment]
Hi, thanks for reporting this to us. This looks to be the same as the kernel issue reported here: https://github.com/amazonlinux/amazon-linux-2023/issues/840#issuecomment-2485782075

As a workaround for the Ruby AL2023 4.2.0 platform versions, you can set the environment variable [UV_USE_IO_URING=0](https://nodejs.org/docs/latest-v21.x/api/cli.html#uv_use_io_uringvalue) when running `npm` or `yarn` commands. This workaround also applies to other platform versions released as part of the [2024-11-21](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2024-11-21-al2023.html) release.

We will have this fixed in the platform release following the next Amazon Linux 2023 kernel update.

**Comment by januszm** [comment]
@praegt  thank you! it works great. I'll close this issue because the workaround is enough until next platform release

**Comment by januszm** [comment]
It'd be great to use this opportunity to also upgrade to node 20 in all base Linux images

**Comment by praegt** [comment]
We are planning to upgrade the provided node.js installation on Ruby AL2023 platforms from v18 to v20 in the next platform release
