### ISSUE TITLE
Sharing Application Load Balancers between environments

### ISSUE THREAD

**Issue by labisso** [aws/elastic-beanstalk-roadmap#40]
**Community Note**
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Description**
We are researching if we can enable new Elastic Beanstalk environments to share an existing [Application Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html) (ALB) with host-header and path based routing. This capability will enable ALBs to be shared across different Beanstalk environments and applications within the same VPC. 

**Feedback requested**
We'd love to hear feedback about this potential feature and how you think it should work. In particular we are wondering about a few details:

1. With this feature, Beanstalk would not be involved in creating the ALB for you. You'd create it separately and then reference it in one or more EB environments. Is that the right workflow?
2. You would not be able to switch a Beanstalk environment between a shared ALB and a Beanstalk-managed ALB. Changing would require creating a new environment. Is this a blocker or concern?
3. Would it be valuable for a Beanstalk-managed ALB from one environment to be used as a shared ALB for another environment?
4. Longer term, we want to support sharing of other resources between environments, such as databases. Is this model the right pattern to use?

**Comment by orestis** [comment]
I would love this. As it stands now my EC2 instances from "Env A" have to talk directly to an ALB to "Env B". If I could share an ALB between them I could just proxy some requests based on path to "Env B".

As long as EB does the right thing with draining connections, auto-registering target groups etc etc, of course.

Specific feedback:

1. I would prefer that, since EB doesn't allow me to specify more than one SSL certificates any way, so I have to deal with that myself. 
2. Would that mean that I'd have to re-create my environments to be able to use a shared ALB? If yes, I think that's OK.
3. Not sure.
4. I think so -- in most cases when starting a new project in AWS, you want to tweak things like the instance size of your ElastiCache cluster, parameter groups of RDS etc -- and that's something best explored via the Console. The EB code is actually stateless, so being able to plug in outside resources makes a ton of sense. Staging/testing environments could spin up self-contained databases, but production environments should point to somewhere external.

**Comment by msitms** [comment]
This would be a big deal for us! We are hosting a number of SaaS applications in Beanstalk, using two Beanstalk environments per customer (testing/production). As the number of customers and environments grows, and the greatly underutilized load balancers eat a significant part of our AWS budget, this is raising concerns whether Elastic Beanstalk is still a viable solution. 

Regarding your questions:

1. Yes, we would create the ALB outside of EB.
2. Depends on the application. Some of our EB applications contain CF stacks with S3 buckets etc. for persisted data. It wouldn't be nice if we would have to recreate them. However, if it is the only option, we would probably rather migrate the data somehow instead of paying for all these load balancers forever.
3. No. We would rather avoid dependencies between environments.
4. This might be useful for many applications, but isn't interesting for our main scenario (environments per tenant).

**Comment by dnorth98** [comment]
I was just thinking of this yesterday while reviewing our AWS bill in these "interesting" times.  ELB is becoming a fairly big component as we have around 100 Beanstalks but they all have quite low request counts - we just use the load balancing for redundancy.

In a past life I did exactly this with ECS based microservices - had a single ALB and used host-header routing to consolidate services to a single ALB instead of an ALB per service.  It worked well!

Specific answers:

1. Yes, we would create the ALB outside of EB (using Terraform in our case)
2. It's not a blocker but what we'd have to do is create temp environments, switch to those temporarily, delete the originals, re-create the originals and then switch back since we have a well defined naming scheme.  By not being able to update in place, it turns a 10 minute task into a day.  Kinda curious why we wouldn't be able to update in place though since I've switched some single-instance environments to load balanced and it worked well (and saved me hours)
3. No.  This would be more confusing I think.
4. Yes I think so.  We've been using this model for worker-tier environments where we create the queues outside of EB and reference them and it works well.  If you're using Infrastructure-as-code, it's easy enough to create and reference a resouce.

**Comment by lvdh** [comment]
> 1. With this feature, Beanstalk would not be involved in creating the ALB for you. You'd create it separately and then reference it in one or more EB environments. Is that the right workflow?

Sounds like an acceptable workflow, sure.

> 2. You would not be able to switch a Beanstalk environment between a shared ALB and a Beanstalk-managed ALB. Changing would require creating a new environment. Is this a blocker or concern?

This sounds fair enough. Drawing the line keeps things manageable on your side.

> 3. Would it be valuable for a Beanstalk-managed ALB from one environment to be used as a shared ALB for another environment?

No, not so much. Rather just use a previously-created, non-EB-managed ALB as you mentioned in (1).

> 4. Longer term, we want to support sharing of other resources between environments, such as databases. Is this model the right pattern to use?

We often get requests for sharing a database instance between (test) EB environments. That said, we hardly ever manage the database through EB. Usually, we create eg. an RDS instance outside of EB and reference it with EB env vars, SSM Parameters or Secrets.

Just my 2 cents, hope this helps. Thank you for launching this request! :+1:

**Comment by JB4GH** [comment]
We are very interested by this feature, as we have a fair amount of EBs and indeed the cost of load balancers is becoming substantial.

We also think that this would be great if the ALB could be shared between applications (not just environments), as most of our EBs could then run behind the same ALB.

1. Sounds good

2. Not a blocker (running the blue/green deployment approach)

3. I don't see the benefit of it, might be useful for some use cases, but I don't see it as a priority

4. Yes

**Comment by kp-autorola** [comment]
This is a very useful feature for us. We currently have some issues adjusting the EB managed load balancer to our needs. Also, the cost for ALBs is also getting quite high, and this feature could reduce it significant. 

1. Yes, we prefer to keep ALB creation outside EB.
2. It would save us time to be able change an existing environment, but it is not a blocker.
3. No, we prefer the approach in #1.
4. Yes, if the shared resource is created outside EB. We already manage our databases outside EB. The same with SQS for worker environments.

**Comment by Sunkyue-Kim** [comment]
1. I don't think so. beanstalk should provide following options when creating environment: 1) use dedicated ALB(like now), 2) attach to existing ALB(with providing appropriate rule template), 3) no ALB (attach manually later or not using)
2. It would be better if switching is possible, but not a big concern if it is not possible.
3. It would make confusion. the dedicated load balancer shouldn't be shared (only if you want to differentiate between dedicate/shared load balancer)
4. I think so. I want to use rds without id/pw authentication when using beanstalk. It would be better if beanstalk could automatically configure attached (whether dedicated or shared) rds for IAM authentication (for security concerns)

**Comment by Ryanauger95** [comment]
This would be fantastic. Dealing with this issue now in 2 separate projects. We would like to do path/host/port/header based routing between different environments and maintain the auto-scaling feature and ease of elastic beanstalk. 

This would be an incredible feature!

**Comment by Ryanauger95** [comment]
Just curious - as we would really like this feature, do you have a timeline at all on when it will be implemented? Thanks!

**Comment by BpTindall** [comment]
I've been looking for this feature for a while now. Our EB count is low, so currently I use EB single instances, and manually add the instance to the Target Groups (except when I forget to do it!).

**Comment by danielnitu** [comment]
This would be great to have as current ALBs are being under-utilised and to use the same ALB for different environments implies a workaround that negates some of the benefits of using EB in the first place. 

1. Yes, as long as we have the option to do that, it's perfect.
2. Not at all.
3. Nice to have, but not a requirement. Creating the ALB ourselves and then attaching it at environment creation is good enough.
4. I think so, but cannot speak for all resources. Sharing ALBs is a great first step.

Could you share any timelines when this might be implemented?
Thanks!

**Comment by MichelZ** [comment]
Absolutely great feature! We could replace like 20 classic LB's with a single ALB! Would save some cost.


  

> With this feature, Beanstalk would not be involved in creating the ALB for you. You'd create it separately and then reference it in one or more EB environments. Is that the right workflow?

Sounds great!
    
> You would not be able to switch a Beanstalk environment between a shared ALB and a Beanstalk-managed ALB. Changing would require creating a new environment. Is this a blocker or concern?

Not a blocker, not a concern for us
    

> Would it be valuable for a Beanstalk-managed ALB from one environment to be used as a shared ALB for another environment?

Not for us. However it would be cool if Beanstalk could add environments automatically to the existing ALB

    

> Longer term, we want to support sharing of other resources between environments, such as databases. Is this model the right pattern to use?

It would be nice if you could share EC2 hosts (i.e. Docker hosts). We don't use databases in EB.

**Comment by macoocoo** [comment]
Absolutely, for all the reasons mentioned above by others. For SME this would be ideal. 

We are small, so recreating from scratch would be possible, although for others this could be a burden.

1. Not a problem, but #3 would resolve it for those new to the concept and make it initially in the same process 

2.no, have you considered copying an environment and allowing certain configurations to be edited before the creation happens? This could make it easier for migtations. (But not at the expense of delaying this as a new feature!)

3. As an option sure, but not as the only way. #1 is more flexible.

4. Possibly. DB not an issue for us as we already have a dedicated RDS and share that.

Good luck and I hope the timelines are near not far!

**Comment by delaney470** [comment]
This would be perfect for us..

1) Yes, we would create the ALB outside of EB.
2) this isn't a blocker, creating new environments is easy and quick
3) No. I prefer the idea of creating the ALB independently of the EB.
4) We already use shared resources by creating them independently of the EB (RDS/S3 Buckets etc), so this does not concern us

This would give us the advantage of Elastic Beanstalks simple deployment and configuration combined with the power of a shared ALB, I would start using this feature immediately if it was available.

**Comment by swaincreates** [comment]
This would be great for us!

1. Yes
2. Not a problem
3. Maybe not a huge value add, but could be useful for sure
4. Not sure

**Comment by MrJohnsson77** [comment]
As the environment grows we'd prefer to manage the ALB outside of the environment, well at least have the option to.

1. Yes
2. No, it's OK
3. Yes, that is also an alternative, however, the first alternative is better.
4. Yes, it's not an issue today though.

**Comment by gilvi** [comment]
Sad this feature is not yet implemented. We'll need to find a workaround to update target groups with the instances from autoscaling groups.

1- Give the option to create a new managed ALB or select one shared.
2- Not blocker, but if able to change from single instance to balanced one, why not to choose the origin of balancer too?
3- A managed one shouldn´t be shareable, but have an option y to convert the managed into a shared one (or at least, to clone it)
4- Yes, once you give the option to create one managed, you should give the option to associate one shared.

**Comment by Sekhar-Kutikuppala** [comment]
Elastic Beanstalk now supports sharing of an Application Load Balancer among Elastic Beanstalk environments. Lear more from this [blog post](https://aws.amazon.com/blogs/containers/amazon-elastic-beanstalk-introduces-support-shared-load-balancers/). 
[What's New](https://aws.amazon.com/about-aws/whats-new/2020/09/aws-elastic-beanstalk-supports-sharing-application-load-balancer-elastic-beanstalk-environments/)
[Documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-alb-shared.html)

**Comment by bruun** [comment]
Thanks for this! We've been able to reduce the number of ALBs in our account by ~75%, which will have a nice impact on our costs.

We have run into an issue with deploying new application versions on environments that use a Shared ALB and _Split-traffic deployments_. The Cloudformation stack fails to create the new target group because it apparently tries to use the same name as the existing target group: `<current-target-group-name> already exists in stack`. 

~When this happens the deploy is automatically attempted aborted, but it doesn't seem to manage this on it's own (or maybe it will time out after a while, currently it has been in the "Aborting" state for >30 minutes).~ It finally completed the abort after ~35 minutes

Using Immutable deploys works as expected, so we've switched to using this deployment strategy for now. Let me know if there is any more information I can provide :)

**Comment by chanlito** [comment]
@bruun can you elaborate more on the process **moving to shared ALB** ? Currently I don't see options to switch in the configuration.

**Comment by bruun** [comment]
@chanlito You can only configure the shared ALB when you create the environment, it's not possible to switch to it in an existing environment.

**Comment by Sekhar-Kutikuppala** [comment]
Hi @bruun, We released the fix for the issue with using Traffic-splitting deployments in Shared ALB environments

**Comment by Ben-CA** [comment]
Would like to see more documentation on the best way to migrate existing Elastic Beanstalk applications to use a Shared Application Load Balancer.

**Comment by uldall** [comment]
We are hitting an issue with using a shared load balancer in a CloudFormation stack containing many EB applications. When launching the stack we get errors like this:
`Service:AmazonElasticLoadBalancing, Message:Priority '4' is currently in use`

Since all the environments are created during a narrow timeframe, some Environments end up registering with the ALB at the same time. This causes some environments to get the same rule priority with the ALB and this is not permitted causing the error observed.  The initial registration is made by Beanstalk and the other rules that I have defined with priority >100 are not causing the problem.

A workaround is to use "DependsOn", but with 30+ environments, this makes the stack creation take hours.
