### ISSUE TITLE
Set environment variables for PHP CLI in Amazon Linux 2

### ISSUE THREAD

**Issue by remarkusable** [aws/elastic-beanstalk-roadmap#72]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
Set the EB environment variables to PHP CLI in Amazon Linux 2.

Currently the environment variables only being set in the PHP-FPM. We need the environment variables to be set in the PHP CLI as well since we have some Composer's post-update script which require the environment variables. Due to this issue, whenever we add/remove environment variables in EB console the config-deploy will fail and we couldn't get the new/edited environment variables since the settings are automatically reverted.

We could have solve this our self if there is config deploy hook like what we have in Amazon Linux 1 and/or if the environment variables are set in the bash shell.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**
PHP 7.4 running on 64bit Amazon Linux 2/3.0.3

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
See above. it's hard to fix since there is no way for us to hook on config-deploy and/or have the environment variables in PHP CLI (for composer.phar)

**Are you currently working around this issue?**
Not possible to solve our self, this need to be fixed by AWS

**Comment by andyexeter** [comment]
This is currently breaking Symfony applications.

After a `composer install`, Symfony compiles its DI container and without proper environment variables set it uses the defaults in its .env file.

This is problematic because the default `APP_ENV` value is `dev` so the container is compiled in development mode rather than production.

It can be worked around by changing the default `APP_ENV` value in .env to `prod` but this is sub-optimal and doesn't resolve issues where other environment variables aren't set or are set to different values.

**Comment by Sekhar-Kutikuppala** [comment]
AL2 platforms now support 'configuration hooks'. See more details [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2020-08-04-al2.html)
