### ISSUE TITLE
Make Env Properties available to build task

### ISSUE THREAD

**Issue by lbruun** [aws/elastic-beanstalk-roadmap#94]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or "me too" comments. They generate extra noise for issue followers and do not help prioritize the request.

**Tell us about your request**
For the AL2 platforms the Environment Properties are not made available to the build task (as specified by `Buildfile`). This looks like a simple oversight to me. If it is a deliberate decision then it should be documented.

**Is this request specific to an Elastic Beanstalk [platform](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html)?**

Issue is specific to platforms which support `Buildfile` (for example: _Java SE - Corretto 8 version 3.1.1_). I've only noticed the problem on AL2 platforms. (actually I suspect the AL2018 platforms did _not_ have this problem)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

We use Buildfile to replace token-placeholders in config files for a legacy application where we do not have the source code, only the binaries. This allows us to use the same source bundle for any environment (production, pilot, uat, dev, etc).

**Are you currently working around this issue?**

Including the "build" part in the command line in `Procfile`. This is obviously sub-optimal.

**Comment by exiareinert-hpa** [comment]
My team would like to use env variables in our `Pipfile` to handle our private PYPI credentials and are unable to, presumably due to this same issue. Platform used is Python 3.7 on AL2. We've also tried exporting the relevant variable in prebuild hooks and setting them in `/etc/profile.d` and `/etc/bashrc`. We haven't been able to find a workaround short of hard-coding our credentials and committing them, which is very much not ideal.

**Comment by 1tonyca** [comment]
This should have been fixed, environment variables in buildfile should be honored. please give it a try, otherwise reopen with current issue for tracking

**Comment by apierce-HomePartners** [comment]
I upgraded to Python 3.8 running on AL2, and during the `InstallDependency` step, my pipfile can no longer read the value of an environment variable that we have set in the configuration. It was able to do so after this fix was applied, when we were running Python 3.7 on AL2. Has this functionality been impacted since the rollout of the Python 3.8 platform?
